### ISSUE TITLE
musl libc support?

### ISSUE THREAD

**Issue by sodomon2** [erikas-taroza/audiotags#15]
Hey, nice library, unfortunately it doesn't have musl support since the precompiled lib is linked against glibc, I was wondering if you could add musl support

or if there is a way to build the `libaudiotags.so` locally

**Comment by erikas-taroza** [comment]
Hello.

I will look into it. It should be possible since there aren't many dependencies.

**Comment by erikas-taroza** [comment]
The binary is now compiled to the `x86_64-unknown-linux-musl` target. Please try the new version 1.4.0
