### ISSUE TITLE
namespace missing from build.grandle

### ISSUE THREAD

**Issue by fendieroo** [erikas-taroza/audiotags#19]
> Namespace not specified. Specify a namespace in the module's build file: C:\Users\Admin\AppData\Local\Pub\Cache\hosted\pub.dev\audiotags-1.4.0\android\build.gradle. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

**Comment by erikas-taroza** [comment]
Are you able to build the example project?

**Comment by josereia** [comment]
I'm having the same problem!

I'm on version 8.5.1 of AGP (Android Gradle Plugin) and Gradle is on version 8.7-all. 
I'm compiling for android with targetSdk 34 and minSdk 22 under flutter version 3.22.2 and dart 3.4.3 stable.

```bash
Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':audiotags'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file: C:\Users\joaol\AppData\Local\Pub\Cache\hosted\pub.dev\audiotags-1.4.0\android\build.gradle. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 2s
Error: Gradle task assembleDebug failed with exit code 1

Exited (1).
```

![image](https://github.com/user-attachments/assets/fbbc93e0-0ada-4523-8399-7eb01a3edc8c)

**Comment by josereia** [comment]
I opened a pull request with a simple solution to the problem, making both the example project and other projects with newer versions of Gradle and AGP compile without problems.

The solution was to add the namespace "com.erikas.audiotags" to build.gralde, remove the package property from AndroidManifest.xml and increase the minSdkVersion to 21. All this to meet Google's requirements for Android, Gradle and AGP.

The only downside is the breaking change as the minimum version of the android sdk had to be set to 21 as this is the minimum version currently supported by Google.

https://github.com/erikas-taroza/audiotags/pull/20
