### ISSUE TITLE
Error parsing file with no tags

### ISSUE THREAD

**Issue by sanihaq** [erikas-taroza/audiotags#3]
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FfiException(RESULT_ERROR, ERR: This file does not have any tags., null)
#0      FlutterRustBridgeBase._transformRust2DartMessage
basic.dart:129
#1      FlutterRustBridgeBase.executeNormal.<anonymous closure>
basic.dart:70
<asynchronous suspension>
#2      AudioTags.read
audiotags.dart:9
<asynchronous suspension>
#3      _FilesListState.build.<anonymous closure>.<anonymous closure>
main.dart:123
<asynchronous suspension>
```
sample file in [attachment](https://github.com/erikas-taroza/audiotags/files/10895126/love-song-10539.mp3.zip) (github doesn't allow mp3 file directly)

**Comment by erikas-taroza** [comment]
The error is intended, just not handled properly. If there are no tags, null will be returned. However, if there is another error (ex. wrong path), that will still be thrown.

Fixed in 04ebbe592dfeede7911771258c3f102940108122. Will publish to pub.dev soon.

**Comment by sanihaq** [comment]
not every image is getting parsed. it's there in file explorer view. is it an error??

**Comment by erikas-taroza** [comment]
> not every image is getting parsed. it's there in file explorer view. is it an error??

Please create a new issue and include the file you are having problems with. I don't have any files with full metadata attached. `audiotags` reads the `CoverFront` image so the image is possibly located under a different name. I can improve the image support.

**Comment by sanihaq** [comment]
@erikas-taroza submitted new issue #4
