### ISSUE TITLE
Not every image is getting parsed

### ISSUE THREAD

**Issue by sanihaq** [erikas-taroza/audiotags#4]
[sample song](https://github.com/erikas-taroza/audiotags/files/10896057/Tere.Pyaar.Mein.-.Tu.Jhoothi.Main.Makkar.mp3.zip)

**Comment by erikas-taroza** [comment]
The issue is `audiotags` tries to get the picture with type `CoverFront`. The file has a picture type of `Other` which is why it didn't retrieve it.

I will work on improving the picture API. I plan on allowing multiple pictures with different formats and types.

**Comment by sanihaq** [comment]
@erikas-taroza Hi, I don't know where to ask this exactly, but…

1. would you mind formatting your rust code according to official style guidelines (use [rust-lang/rustfmt)](https://github.com/rust-lang/rustfmt)
2. if not, would you mind providing a `.editorconfig`(or similar for vscode) file.
3. overall, make this and “simple_audio” more friendly to other contributors.

Anyway, thanks for this and other amazing package. Keep up the good work.  👍

**Comment by erikas-taroza** [comment]
> 1\. would you mind formatting your rust code according to official style guidelines (use [rust-lang/rustfmt)](https://github.com/rust-lang/rustfmt)

Sure.



> 3\. overall, make this and “simple_audio” more friendly to other contributors.

These are my first open source projects that I have published. I apologize if some things are missing. Could you give some suggestions?

**Comment by sanihaq** [comment]
@erikas-taroza you should create a CONTRIBUTING.md file explaining setting up the project or any other advice, rules to follow. 
There are other files you can include, like a CODE_OF_CONDUCT file. 
A LICENSE file is a must.

For this project, flutter_rust_bridge will be a new thing for most newcomers. So a bit of explanation about that will be helpful. For me, I'm not really sure how you set that up with your project.

**Comment by erikas-taroza** [comment]
I see. I will take this into account. It's getting late for me so I will do this tomorrow.

**Comment by sanihaq** [comment]
@erikas-taroza take your time. good night.

**Comment by erikas-taroza** [comment]
I have updated `pub.dev` with the latest version. You should be able to fetch all the pictures as well as write multiple. I will make the repo more contributor friendly.
