### ISSUE TITLE
Windows build failed.

### ISSUE THREAD

**Issue by sanihaq** [erikas-taroza/audiotags#5]
```
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\dxgi.h(1,1): error C2220: the following warning is treated as an error [C:\Users\sani\Documents\GitHub\simple_music_player\build\windows\plugins\audiotags\audiotags_plugin.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\dxgi.h(1,1): warning C4821: Unable to determine Unicode encoding type, please save the file with signature (BOM) [C:\Users\sani\Documents\GitHub\simple_music_player\build\windows\plugins\audiotags\audiotags_plugin.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\winapifamily.h(1,1): warning C4821: Unable to determine Unicode encoding type, please save the file with signature (BOM) [C:\Users\sani\Documents\GitHub\simple_music_player\build\windows\plugins\audiotags\audiotags_plugin.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\sdkddkver.h(1,1): warning C4821: Unable to determine Unicode encoding type, please save the file with signature (BOM) [C:\Users\sani\Documents\GitHub\simple_music_player\build\windows\plugins\audiotags\audiotags_plugin.vcxproj]
C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\windows.h(32,28): warning C4067: unexpected tokens following preprocessor directive - expected a newline [C:\Users\sani\Documents\GitHub\simple_music_player\build\windows\plugins\audiotags\audiotags_plugin.vcxproj]
C:\Users\sani\Documents\GitHub\simple_music_player\windows\flutter\ephemeral\flutter_windows.h(121,5): error C2061: syntax error: identifier 'HWND' 
...
...
C:\Users\sani\Documents\GitHub\simple_music_player\windows\flutter\ephemeral\cpp_client_wrapper\include\flutter/plugin_registrar_windows.h(96,9): error C2451: a conditional expression of type 'std::optional' is not valid [C:\Users\sani\Documents\GitHub\simple_music_player\build\windows\plugins\simple_audio\simple_audio_plugin.vcxproj]
C:\Users\sani\Documents\GitHub\simple_music_player\windows\flutter\ephemeral\cpp_client_wrapper\include\flutter/plugin_registrar_windows.h(97,8): error C2065: 'result': undeclared identifier [C:\Users\sani\Documents\GitHub\simple_music_player\build\windows\plugins\simple_audio\simple_audio_plugin.vcxproj]
Building Windows application...
Exception: Build process failed.
```

**Comment by erikas-taroza** [comment]
I will take a look at this when I have the time.

**Comment by erikas-taroza** [comment]
Hello.

I am able to build and run the example app with no errors. Maybe try `flutter clean`?

**Comment by sanihaq** [comment]
@erikas-taroza not sure if its this packages fault but got this error after upgrading to audoitags 1.1.1.

```
lib/main.dart(16,7): error GC9768DF9: Undefined name 'NotificationActions'. [C:\Users\sani\Documents\GitHub\simple_music_player\build\windows\flutter\flutter_assemble.vcxproj]
lib/main.dart(17,7): error GC9768DF9: Undefined name 'NotificationActions'. [C:\Users\sani\Documents\GitHub\simple_music_player\build\windows\flutter\flutter_assemble.vcxproj]
lib/main.dart(14,5): error GC6690633: No named parameter with the name 'androidCompactPlaybackActions'. [C:\Users\sani\Documents\GitHub\simple_music_player\build\windows\flutter\flutter_assemble.vcxproj]
lib/utils/utils.dart(34,30): error G75B77105: Member not found: 'Icon'. [C:\Users\sani\Documents\GitHub\simple_music_player\build\windows\flutter\flutter_assemble.vcxproj]
lib/utils/utils.dart(35,24): error G75B77105: Member not found: 'Png'. [C:\Users\sani\Documents\GitHub\simple_music_player\build\windows\flutter\flutter_assemble.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB8066: Custom build for 'C:\Users\sani\Documents\GitHub\simple_music_player\build\windows\CMakeFiles\346ec51341759c40164bbd4237fd13ff\flutter_windows.dll.rule;C:\Users\sani\Documents\GitHub\simple_music_player\build\windows\CMakeFiles\b16c681d098d89377f86e7eb3427e6e6\flutter_assemble.rule' exited with code 1. [C:\Users\sani\Documents\GitHub\simple_music_player\build\windows\flutter\flutter_assemble.vcxproj]
Building Windows application...
Exception: Build process failed.
```

**Comment by erikas-taroza** [comment]
> @erikas-taroza not sure if its this packages fault but got this error after upgrading to audoitags 1.1.1 (previously using 1.1.0).
> 
> ```
> lib/main.dart(16,7): error GC9768DF9: Undefined name 'NotificationActions'. [C:\Users\sani\Documents\GitHub\simple_music_player\build\windows\flutter\flutter_assemble.vcxproj]
> lib/main.dart(17,7): error GC9768DF9: Undefined name 'NotificationActions'. [C:\Users\sani\Documents\GitHub\simple_music_player\build\windows\flutter\flutter_assemble.vcxproj]
> lib/main.dart(14,5): error GC6690633: No named parameter with the name 'androidCompactPlaybackActions'. [C:\Users\sani\Documents\GitHub\simple_music_player\build\windows\flutter\flutter_assemble.vcxproj]
> lib/utils/utils.dart(34,30): error G75B77105: Member not found: 'Icon'. [C:\Users\sani\Documents\GitHub\simple_music_player\build\windows\flutter\flutter_assemble.vcxproj]
> lib/utils/utils.dart(35,24): error G75B77105: Member not found: 'Png'. [C:\Users\sani\Documents\GitHub\simple_music_player\build\windows\flutter\flutter_assemble.vcxproj]
> C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB8066: Custom build for 'C:\Users\sani\Documents\GitHub\simple_music_player\build\windows\CMakeFiles\346ec51341759c40164bbd4237fd13ff\flutter_windows.dll.rule;C:\Users\sani\Documents\GitHub\simple_music_player\build\windows\CMakeFiles\b16c681d098d89377f86e7eb3427e6e6\flutter_assemble.rule' exited with code 1. [C:\Users\sani\Documents\GitHub\simple_music_player\build\windows\flutter\flutter_assemble.vcxproj]
> Building Windows application...
> Exception: Build process failed.
> ```

Please read the changelog. Breaking changes were added.

**Comment by sanihaq** [comment]
@erikas-taroza please follow semver rule 0.[breaking change].[bug fix]

Sorry, it was my fault to not check my code beforehand.

**Comment by erikas-taroza** [comment]
> @erikas-taroza please follow semver rule 0.[breaking change].[bug fix]

Ah sorry. I will keep in mind :)

**Comment by sanihaq** [comment]
@erikas-taroza didn't really solve the problem, I'm trying it in brand-new instance in a vm. do I have to do any setup beforehand?

**Comment by erikas-taroza** [comment]
> @erikas-taroza didn't really solve the problem, I'm trying it in brand-new instance in a vm. do I have to do any setup beforehand?

Should work OOTB. Maybe you need to update the Windows SDK via Visual Studio?
