### ISSUE TITLE
[Feature request] Add track number field to metadata

### ISSUE THREAD

**Issue by dannyglover** [erikas-taroza/audiotags#6]
Hey, thanks for this great flutter plugin.

Do you have any plans to add more fields to the exposed metadata? Support for the track number would be great.
Thank you.

**Comment by erikas-taroza** [comment]
> Hey, thanks for this great flutter plugin.
> 
> Do you have any plans to add more fields to the exposed metadata? Support for the track number would be great. Thank you.

Sure, I will implement support for this.

**Comment by dannyglover** [comment]
> > Hey, thanks for this great flutter plugin.
> > Do you have any plans to add more fields to the exposed metadata? Support for the track number would be great. Thank you.
> 
> Sure, I will implement support for this.

Thanks Erikas. Unrelated question...

I have a largeish music collection (1000 songs) and I'm getting errors reading the tags for various files (errors drilling down into your plugin) along with invalid picture data (using MemoryImage).

As the cause of this could be due to numerous things (filenames, special characters etc, bad metadata), it could be hard to reproduce at your end.

Would giving you read access to the music on my dropbox account help in diagnosing these problems at your end?
Thanks again.

**Comment by erikas-taroza** [comment]
The files will help with debugging. You can compile a list of problem files and send them as a zip as an attachment.

**Comment by dannyglover** [comment]
> The files will help with debugging. You can compile a list of problem files and send them as a zip as an attachment.

Thanks. I created a separate issue for that, to keep this one on topic. https://github.com/erikas-taroza/audiotags/issues/7

**Comment by erikas-taroza** [comment]
Ok thank you.

I have added support for the track number and track total metadata fields in ccbda92
Let me know if need any other fields. I will be happy to add them.

**Comment by dannyglover** [comment]
> Ok thank you.
> 
> I have added support for the track number and track total metadata fields in [ccbda92](https://github.com/erikas-taroza/audiotags/commit/ccbda921b8c2d21525c01365649ced03f534d92b) Let me know if need any other fields. I will be happy to add them.

You work fast! Thank you very much.

I do have a list of other fields that would be great to have. I'll open a new issue for those.

PS: do you have a build bot that builds a new version of the plugin and pushes it live to pub.dev?

Thanks again.

**Comment by erikas-taroza** [comment]
> I do have a list of other fields that would be great to have. I'll open a new issue for those.

Ok sounds good.

> PS: do you have a build bot that builds a new version of the plugin and pushes it live to pub.dev?
No. I have a CD that creates the libraries and uploads them as a GitHub release asset. I still upload to pub.dev manually.
