### ISSUE TITLE
[Documentation] add documentation on building the plugin  

### ISSUE THREAD

**Issue by dannyglover** [erikas-taroza/audiotags#8]
Me again :)

I'd like to contribute to this plugins development, but am unsure how to get started, in regards to setting up the build environment.

I'm on Linux, so I guess I'd like documentation for building the plugin on Linux initially. I'm experienced with C/C++/Dart/C#/Lua. Admittedly, I haven't done any rust development yet, but I'm a fast learner.

Thanks again.

**Comment by erikas-taroza** [comment]
Please read [CONTRIBUTING.md](https://github.com/erikas-taroza/audiotags/blob/master/CONTRIBUTING.md)

Basically, all you need is the Rust language and Python. Python is used to run the `plugin_tool.py` script.

**Comment by erikas-taroza** [comment]
You may also have to use [this](https://cjycode.com/flutter_rust_bridge/troubleshooting.html#the-generated-store_dart_post_cobject-has-the-wrong-signature--stdargh-file-not-found-in-linux--stdboolh--) env var if the codegen doesn't have correct results.

**Comment by dannyglover** [comment]
I was able to get it all up and running. 
Thanks
