### ISSUE TITLE
[Feature] Add more metadata fields

### ISSUE THREAD

**Issue by dannyglover** [erikas-taroza/audiotags#9]
Here are some more fields that would be great to add support for:

```
tag.trackArtist, -- added via https://github.com/erikas-taroza/audiotags/pull/10
tag.albumArtist -- added via https://github.com/erikas-taroza/audiotags/pull/10
tag.originalReleaseDate,
tag.trackNumber -- already supported
tag.trackTotal -- already supported
tag.discNumber -- added via https://github.com/erikas-taroza/audiotags/pull/10
tag.discTotal -- added via https://github.com/erikas-taroza/audiotags/pull/10
```
All of these fields are available in lofty.
I know you already have the `tag.artist` field, but having both track artist and album artist fields would be great. I believe you recently added `tag.trackNumber`, from my previous feature request, so feel free to ignore that.

Thanks again Erikas!

PS: I've been working on setting up my dev environment, so I may chip in to adding support for some of these fields, as it would be a good first assignment in familiarizing myself with your codebase.

Cheers :)

**Comment by erikas-taroza** [comment]
> PS: I've been working on setting up my dev environment, so I may chip in to adding support for some of these fields, as it would be a good first assignment in familiarizing myself with your codebase.

These changes are pretty simple to feel free to PR. For `recordingDate` and `originalReleaseDate`, you will have to use [`chrono`](https://crates.io/crates/chrono) to handle dates in Rust.

**Comment by dannyglover** [comment]
First PR ready for review (implements two of my requested fields) https://github.com/erikas-taroza/audiotags/pull/10
